# Generated by Django 2.0 on 2018-10-27 13:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='iot.png', upload_to='')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('breif', models.TextField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='documentation_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
