# Generated by Django 2.0 on 2018-09-08 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
