# Generated by Django 2.0 on 2018-09-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_lamp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamp',
            name='description',
        ),
    ]
