# Generated by Django 2.0 on 2018-11-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0004_auto_20181027_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='any',
        ),
    ]
