# Generated by Django 2.0 on 2019-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0006_auto_20190112_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='plant.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='robot',
            name='image',
            field=models.ImageField(default='robot.png', upload_to=''),
        ),
    ]
