# Generated by Django 2.0 on 2019-01-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0007_auto_20190113_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='humidity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
